// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoPlayController from "./auto_play_controller"
application.register("auto-play", AutoPlayController)

import CountryController from "./country_controller"
application.register("country", CountryController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
