// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActionNoticeController from "./action_notice_controller"
application.register("action-notice", ActionNoticeController)

import AutoPlayController from "./auto_play_controller"
application.register("auto-play", AutoPlayController)

import CardSelectController from "./card_select_controller"
application.register("card-select", CardSelectController)

import CountryController from "./country_controller"
application.register("country", CountryController)

import DialogController from "./dialog_controller"
application.register("dialog", DialogController)

import GameBoardFeedController from "./game_board_feed_controller"
application.register("game-board-feed", GameBoardFeedController)

import GameBoardSelectionController from "./game_board_selection_controller"
application.register("game-board-selection", GameBoardSelectionController)

import GameBoardTabsController from "./game_board_tabs_controller"
application.register("game-board-tabs", GameBoardTabsController)

import GameBoardToastController from "./game_board_toast_controller"
application.register("game-board-toast", GameBoardToastController)

import GofishTurnController from "./gofish_turn_controller"
application.register("gofish-turn", GofishTurnController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import OfflineController from "./offline_controller"
application.register("offline", OfflineController)

import ServiceWorkerController from "./service_worker_controller"
application.register("service-worker", ServiceWorkerController)

import TimerController from "./timer_controller"
application.register("timer", TimerController)
